title: Random Thoughts
description: Warranty void.
baseurl: ""
url: "https://vcsjones.com"
twitter_username: vcsjones
github_username:  vcsjones
permalink: /:year/:month/:day/:title/

markdown: kramdown
paginate: 1
gems:
  - jekyll-paginate
exclude:
  - app.js
  - package.json
  - node_modules
  - gulpfile.js
  - publish.sh
  - appspec.yml
  