title: Random Thoughts
description: Warranty void.
baseurl: ""
url: "https://vcsjones.dev"
twitter_username: vcsjones
github_username:  vcsjones
permalink: /:year/:month/:day/:title/

markdown: kramdown
paginate: 5
sass:
  sourcemap: never
plugins:
  - jekyll-paginate
exclude:
  - appspec.yml
  - _deploy
  - _server
  - README.md
  - .gitignore
  - .devcontainer.json
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - buildspec.yml
  