version: 0.0
os: linux
files:
  - source: _site
    destination: /var/wwwroot/vcsjones.com
  - source: _server/Caddyfile
    destination: /etc/caddy/

permissions:
  - object: /var/wwwroot/vcsjones.com
    owner: root
    group: root
    mode: 775
    type:
      - directory

  - object: /var/wwwroot/vcsjones.com
    owner: root
    group: root
    mode: 775
    type:
      - file

hooks:
  AfterInstall:
    - location: _deploy/reload.sh