version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y webp exiftool pngcrush gzip git cmake
      - git clone https://github.com/google/brotli.git /tmp/brotli
      - pushd /tmp/brotli && git checkout v1.0.7 && popd
      - mkdir /tmp/brotli/out
      - pushd /tmp/brotli/out && ../configure-cmake --disable-debug && make && make install && popd

  build:
    commands:
      - gem install bundler
      - bundle install
      - bundle exec jekyll
      - bundle exec rake

artifacts:
  files:
    - _site/**/*
  name: site